### ISSUE TITLE
Alarms fail to trigger

### ISSUE THREAD

**Issue by coopooc** [jhagberg/ESP8266TimeAlarms#1]
It seems like the library just doesn't like some alarm times. I've noticed all alarms will fire perfectly, I'll change the times (being careful to follow the proper format) and none will fire. I discovered that it doesn't like a leading zero as in 8, 05, 0 but it seems there are other numbers that will trip it up. Can anyone shed any light on this?

**Comment by jhagberg** [comment]
Hej. Sorry missed this. Can you ad some examples of code that fails and codes that works. So I can do some testing?

**Comment by coopooc** [comment]
Ahh, I literally JUST blew up my previous version last night and started an attempt to go back to the main fork. I bet I still have the old one though. I'll send it. Thanks so much for your willingness to help! My daughter's (currently) dark fish tank will be grateful. Ha!

**Comment by coopooc** [comment]
Looks like I already uploaded it to github: You can look at it here: https://github.com/coopooc/aquarium
Based on my memory, the most recent state was unreliable alarms. Some combinations of times would allow it to go through a full cycle but then quit working on the next cycle but most combinations of times wouldn't work at all. 

Thanks a ton for your help. Hopefully I just made a dumb mistake somewhere.

**Comment by jhagberg** [comment]
Hej

I have a bit of limited time this week, can you help out and create just a sketch with the TimeAlarms and simple Serial output instead of the sunrise things. So we can rule out the TimeAlarm library.

**Comment by coopooc** [comment]
I appreciate your offer to help but I ended up going back to the main PaulStoffregen library (and swapping out the NTP method) and all the alarms seem to be working properly now.

**Comment by jhagberg** [comment]
okey thats not very helpful if you found a bug here. But I did not have any problem with the alarms and I have not changed the alarm code just the way time is handled. So it should not be a problem with the changes. But it would be good if we could find any bug.

**Comment by coopooc** [comment]
Sorry! My coding skills would be described as "weak, at best". Stripping the sketch down to just the alarms and serial output...and getting it to actually compile....would have taken me forever. Or rather, I would have just needed to start from scratch with only those elements and, truth be told, it probably would have worked just fine. I doubt your library was at fault if nobody else has submitted a similar bug. It was strange that certain combinations of times worked while others didn't but it just as likely could have been caused by the NTP code failing to work or something unrelated.

**Comment by jhagberg** [comment]
Okey what was not working. Just the alarm trigger or something in your function? can you describe it?

**Comment by coopooc** [comment]
Yeah so, the alarms basically just ran a function that would change booleans from false to true. Then in the loop another function would execute an animation if the boolean was true. I had the serial printing the contents of the booleans and the current time. That way, I could see if an alarm triggered or not based on the time and the status of the boolean constants. If they showed 1 after the alarm was supposed to trigger, I knew it was working. 

So, the odd thing was, I was only changing one variable at a time, the alarm time. So, say it was set for 8:01. Compile upload wait till 8:01 and let's say it worked. Then I'd want it to go at 9:23 and would ONLY change the time for example. I'd get to that time, confirm the time on the serial monitor, and the function had never been triggered and the constant still showed as 0. Ok, I change it to 9:26, doesn't work. Change it to 9:27, works fine. 

Those times are all just examples. Really strange behavior that I could never figure out a pattern to. Like I said though, it's just as likely that some other function was preventing the alarm library from working properly. I DID swap out the internet time code I was using. I feel like that's the most likely culprit at this point. 

Thanks again for trying to help me. I'm sorry I can't provide you with better information.
