### ISSUE TITLE
Memory usage of Alarm is 40 bytes instead of 11

### ISSUE THREAD

**Issue by hjkoster400d** [jhagberg/ESP8266TimeAlarms#11]
The documentation states that the memory usage of an alarm struct is 11 bytes.
This appears to be 40 bytes, so maybe the documentation can be updated ;)

**Comment by jhagberg** [comment]
Absolutely, suggest changes with a PR. I am not actively working with this lib. So all help is welcome

**Comment by hjkoster400d** [comment]
Done, PR is open

**Comment by jhagberg** [comment]
Fixed by #12
