### ISSUE TITLE
NTP Time

### ISSUE THREAD

**Issue by vangalvin** [jhagberg/ESP8266TimeAlarms#2]
This may be a silly question but is is the time contentiously being obtained from the NTP time server on the example or is the internal clock being set once the the time is obtained from that?

initially I was building a project that Incorporated an RTC but since the unit will always have net connectivity decided to opt for using NTP instead. What i did not want to do it spam the NTP serer with requests every second when i am passing the time back to the display.

What i was not sure about is when you set the following...
configTime(0, 0, "0.nz.pool.ntp.org");
setenv("TZ", "NZST-12NZDT,M9.5.0,M4.1.0/3", 1);
tzset();

then call something like

  time_t hnow;
  struct tm * timeinfo;
  time(&hnow);
  timeinfo = localtime(&hnow);

Is that triggering communication from the time server ?

**Comment by jhagberg** [comment]
That's a good question. I thought about it myself and I think I searched for it in the source code. But unfortunately I can't remember now. Need to check again or do some network testing.

**Comment by jhagberg** [comment]
It updates every hour before default.
But you can change it look at these comments

https://github.com/esp8266/Arduino/issues/4559#issuecomment-376196319
