### ISSUE TITLE
Alarm.timerRepeat(Hour, Minute, Second, TimerFunction); Does not create unless TZ = GMT

### ISSUE THREAD

**Issue by mackrasp** [jhagberg/ESP8266TimeAlarms#7]
This alarm function fails to be created if I set to my local timezone to WST-8 (Perth Western Australia)
if I set Alarm.timerRepeat(0, 1, 0, TimerFunction); after getting the correct NTP time with 
 configTime(0, 0, "ntp.aussiebroadband.com.au"); 
 setenv("TZ", "WST-8", 1);
 tzset();
It appears that t2-previousMidnight(t1) is then calculated as -28740
If I set my time zone to GMT it is created and works correctly and
t2-previousMidnight(t1) is then calculated as 60

**Comment by jeanlemotan** [comment]
I added a PR for this: https://github.com/jhagberg/ESP8266TimeAlarms/pull/8

**Comment by jhagberg** [comment]
Thanks for this and for the PR!
